export enum NAVIGATION {
  NEXT = 1,
  PREVIOUS = 0,
}

export enum LANGUAGE {
  FRANCAIS = "fr",
  ANGLAIS = "en",
  ALLEMAND = "de",
  ITALIEN = "it",
  ESPAGNOLE = "es",
}
export enum URL_POKEMON {
  CURRENT = "https://pokeapi.co/api/v2/pokemon-species?offset=0&limit=9",
}

export enum TRADUCTION_FR {
  POKEDEX_NAME = "NOM DE VOTRE POKÉDEX",
  ENTRER_VOTRE_NOM = "ENTREZ VOTRE NOM",
  CHOISIR_LANGUE = "CHOISIR UNE LANGUE",
  CREER_POKEDEX = "CRÉER MON POKEDEX",
  CHERCHER_UN_POKEMON = "chercher un POKEMON",
  POKEMON_CONSULTE = "Pokémon que vous consultez est : ",
  TITRE_NOM = "NOM",
  TITRE_TYPE = "TYPE",
  TITRE_MORPHOLOGIE = "MORPHOLOGIE",
  TITRE_STATS = "STATS",
  TITRE_DESCRIPTION = "DESCRIPTION",
  POKEMON_POIDS = "POIDS",
  POKEMON_TAILLE = "TAILLE",
}

export enum TRADUCTION_EN {
  POKEDEX_NAME = "NAME OF YOUR POKEDEX",
  ENTRER_VOTRE_NOM = "PLEASE ENTER YOUR NAME",
  CHOISIR_LANGUE = "CHOOSE LANGUAGE",
  CREER_POKEDEX = "CREATE POKEDEX",
  CHERCHER_UN_POKEMON = "Search for a POKEMON",
  POKEMON_CONSULTE = "Pokémon that your are consulting is : ",
  TITRE_NOM = "NAME",
  TITRE_TYPE = "TYPE",
  TITRE_MORPHOLOGIE = "MORPHOLOGY",
  TITRE_STATS = "STATS",
  TITRE_DESCRIPTION = "DESCRIPTION",
  POKEMON_POIDS = "WEIGHT",
  POKEMON_TAILLE = "HEIGHT",
}

export enum TRADUCTION_DE {
  POKEDEX_NAME = "NAME IHRES POKÉDEX",
  ENTRER_VOTRE_NOM = "GIB DEINEN NAMEN EIN",
  CHOISIR_LANGUE = "SPRACHE WÄHLEN",
  CREER_POKEDEX = "MEIN POKEDEX ERSTELLEN",
  CHERCHER_UN_POKEMON = "Suche nach einem POKEMON",
  POKEMON_CONSULTE = "Pokémon, das Sie konsultieren, ist: ",
  TITRE_NOM = "NAME",
  TITRE_TYPE = "TYP",
  TITRE_MORPHOLOGIE = "MORPHOLOGIE",
  TITRE_STATS = "STATS",
  TITRE_DESCRIPTION = "BESCHREIBUNG",
  POKEMON_POIDS = "GEWICHT",
  POKEMON_TAILLE = "GRÖSSE",
}

export enum TRADUCTION_IT {
  POKEDEX_NAME = "NOME DEL TUO POKEDEX",
  ENTRER_VOTRE_NOM = "INSERISCI IL TUO NOME",
  CHOISIR_LANGUE = "SCEGLI UNA LINGUA",
  CREER_POKEDEX = "CREA IL MIO POKEDEX",
  CHERCHER_UN_POKEMON = "Cercare un POKEMON",
  POKEMON_CONSULTE = "Il Pokémon che stai consultando è: ",
  TITRE_NOM = "NOME",
  TITRE_TYPE = "TIPO",
  TITRE_MORPHOLOGIE = "MORFOLOGIA",
  TITRE_STATS = "STATICHE",
  TITRE_DESCRIPTION = "DESCRIZIONE",
  POKEMON_POIDS = "PESO",
  POKEMON_TAILLE = "DIMENSIONI",
}

export enum TRADUCTION_ES {
  POKEDEX_NAME = "NOMBRE DE TU POKEDEX",
  ENTRER_VOTRE_NOM = "INTRODUZCA SU NOMBRE",
  CHOISIR_LANGUE = "ELIJA UN IDIOMA",
  CREER_POKEDEX = "CREAR MI POKEDEX",
  CHERCHER_UN_POKEMON = "Busca un POKEMON",
  POKEMON_CONSULTE = "El Pokémon que estás consultando es:  ",
  TITRE_NOM = "NOMBRE",
  TITRE_TYPE = "TIPO",
  TITRE_MORPHOLOGIE = "MORFOLOGÍA",
  TITRE_STATS = "ESTADÍSTICAS",
  TITRE_DESCRIPTION = "DESCRIPCIÓN",
  POKEMON_POIDS = "PESO",
  POKEMON_TAILLE = "TALLA",
}
